sudo: required
dist: trusty

addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - libxml2-utils
      - wget
      # Package list from http://bazel.io/docs/install.html
      - pkg-config
      - zip
      - unzip
      - zlib1g-dev
jdk:
  - oraclejdk8

before_install:
  - wget 'https://github.com/bazelbuild/bazel/releases/download/0.5.4/bazel-0.5.4-installer-linux-x86_64.sh'
  - chmod +x bazel-0.5.4-installer-linux-x86_64.sh
  - ./bazel-0.5.4-installer-linux-x86_64.sh --user
  - mv .bazelrc.travis .bazelrc
  - bash travisdeps.sh

script:
  - bash travis.sh

cache:
  directories:
    - deps
    - ~/bazel

after_success:
  - bash package.sh

deploy:
  provider: gcs
  access_key_id: GOOG47VSCMOXXSBAZ2NU
  secret_access_key:
    secure: cXh6WQUKjgdW6no2D1hDuk1CwToHA1eXKu6uQSl2sL9u1iAi4szGcu6Eu+H1x6qWK2xY7HFlutBfJ7HgicWe0qiIneCr/tPO88znOAOjuCxTUvZ4R3kjRzYUeS/n+3B3wVT5wAUyKKWzhOkdFFyCx14029a+n8bIuoefq5wOv2U=
  bucket: livegrep.appspot.com
  skip_cleanup: true
  acl: public-read
  upload_dir: builds
  local_dir: builds
  on:
    all_branches: true
