version: 2
jobs:
  build:
    docker:
      - image: us.gcr.io/livegrep/ci:5

    steps:
      - checkout
      - restore_cache:
          keys:
            - bazel-cache

      - run: ./.circleci/build.sh
