FROM mcr.microsoft.com/devcontainers/base:alpine-3.16
RUN apk add clang fish abseil-cpp-dev \
    boost-dev \
    protoc \
    unzip \ 
    curl \ 
    protobuf-dev \ 
    gflags-dev \
    gtest-dev \
    benchmark-dev grpc-dev libgit2-dev